spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: hgfhgfhfgh5y65y
            client-secret: ghgfhfghfghfg
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email